/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ListingIdRouteImport } from './routes/listing/$id'
import { Route as CompareZillowRouteImport } from './routes/compare/zillow'
import { Route as CompareWritesonicRouteImport } from './routes/compare/writesonic'
import { Route as CompareVirtualstagingaiRouteImport } from './routes/compare/virtualstagingai'
import { Route as CompareReimaginehomeRouteImport } from './routes/compare/reimaginehome'
import { Route as CompareRealtorRouteImport } from './routes/compare/realtor'
import { Route as CompareListingrobotRouteImport } from './routes/compare/listingrobot'
import { Route as CompareListingaiRouteImport } from './routes/compare/listingai'
import { Route as CompareKvcoreRouteImport } from './routes/compare/kvcore'
import { Route as CompareJasperRouteImport } from './routes/compare/jasper'
import { Route as CompareHomebotRouteImport } from './routes/compare/homebot'
import { Route as CompareGrammarlyRouteImport } from './routes/compare/grammarly'
import { Route as CompareFollowupbossRouteImport } from './routes/compare/followupboss'
import { Route as CompareEpiqueRouteImport } from './routes/compare/epique'
import { Route as CompareDealmachineRouteImport } from './routes/compare/dealmachine'
import { Route as CompareCuraytorRouteImport } from './routes/compare/curaytor'
import { Route as CompareCopyaiRouteImport } from './routes/compare/copyai'
import { Route as CompareChatgptRouteImport } from './routes/compare/chatgpt'
import { Route as CompareCanvaRouteImport } from './routes/compare/canva'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareZillowRoute = CompareZillowRouteImport.update({
  id: '/compare/zillow',
  path: '/compare/zillow',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareWritesonicRoute = CompareWritesonicRouteImport.update({
  id: '/compare/writesonic',
  path: '/compare/writesonic',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareVirtualstagingaiRoute = CompareVirtualstagingaiRouteImport.update({
  id: '/compare/virtualstagingai',
  path: '/compare/virtualstagingai',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareReimaginehomeRoute = CompareReimaginehomeRouteImport.update({
  id: '/compare/reimaginehome',
  path: '/compare/reimaginehome',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRealtorRoute = CompareRealtorRouteImport.update({
  id: '/compare/realtor',
  path: '/compare/realtor',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareListingrobotRoute = CompareListingrobotRouteImport.update({
  id: '/compare/listingrobot',
  path: '/compare/listingrobot',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareListingaiRoute = CompareListingaiRouteImport.update({
  id: '/compare/listingai',
  path: '/compare/listingai',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareKvcoreRoute = CompareKvcoreRouteImport.update({
  id: '/compare/kvcore',
  path: '/compare/kvcore',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareJasperRoute = CompareJasperRouteImport.update({
  id: '/compare/jasper',
  path: '/compare/jasper',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareHomebotRoute = CompareHomebotRouteImport.update({
  id: '/compare/homebot',
  path: '/compare/homebot',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareGrammarlyRoute = CompareGrammarlyRouteImport.update({
  id: '/compare/grammarly',
  path: '/compare/grammarly',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFollowupbossRoute = CompareFollowupbossRouteImport.update({
  id: '/compare/followupboss',
  path: '/compare/followupboss',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareEpiqueRoute = CompareEpiqueRouteImport.update({
  id: '/compare/epique',
  path: '/compare/epique',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareDealmachineRoute = CompareDealmachineRouteImport.update({
  id: '/compare/dealmachine',
  path: '/compare/dealmachine',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCuraytorRoute = CompareCuraytorRouteImport.update({
  id: '/compare/curaytor',
  path: '/compare/curaytor',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCopyaiRoute = CompareCopyaiRouteImport.update({
  id: '/compare/copyai',
  path: '/compare/copyai',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareChatgptRoute = CompareChatgptRouteImport.update({
  id: '/compare/chatgpt',
  path: '/compare/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareCanvaRoute = CompareCanvaRouteImport.update({
  id: '/compare/canva',
  path: '/compare/canva',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/canva': typeof CompareCanvaRoute
  '/compare/chatgpt': typeof CompareChatgptRoute
  '/compare/copyai': typeof CompareCopyaiRoute
  '/compare/curaytor': typeof CompareCuraytorRoute
  '/compare/dealmachine': typeof CompareDealmachineRoute
  '/compare/epique': typeof CompareEpiqueRoute
  '/compare/followupboss': typeof CompareFollowupbossRoute
  '/compare/grammarly': typeof CompareGrammarlyRoute
  '/compare/homebot': typeof CompareHomebotRoute
  '/compare/jasper': typeof CompareJasperRoute
  '/compare/kvcore': typeof CompareKvcoreRoute
  '/compare/listingai': typeof CompareListingaiRoute
  '/compare/listingrobot': typeof CompareListingrobotRoute
  '/compare/realtor': typeof CompareRealtorRoute
  '/compare/reimaginehome': typeof CompareReimaginehomeRoute
  '/compare/virtualstagingai': typeof CompareVirtualstagingaiRoute
  '/compare/writesonic': typeof CompareWritesonicRoute
  '/compare/zillow': typeof CompareZillowRoute
  '/listing/$id': typeof ListingIdRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/canva': typeof CompareCanvaRoute
  '/compare/chatgpt': typeof CompareChatgptRoute
  '/compare/copyai': typeof CompareCopyaiRoute
  '/compare/curaytor': typeof CompareCuraytorRoute
  '/compare/dealmachine': typeof CompareDealmachineRoute
  '/compare/epique': typeof CompareEpiqueRoute
  '/compare/followupboss': typeof CompareFollowupbossRoute
  '/compare/grammarly': typeof CompareGrammarlyRoute
  '/compare/homebot': typeof CompareHomebotRoute
  '/compare/jasper': typeof CompareJasperRoute
  '/compare/kvcore': typeof CompareKvcoreRoute
  '/compare/listingai': typeof CompareListingaiRoute
  '/compare/listingrobot': typeof CompareListingrobotRoute
  '/compare/realtor': typeof CompareRealtorRoute
  '/compare/reimaginehome': typeof CompareReimaginehomeRoute
  '/compare/virtualstagingai': typeof CompareVirtualstagingaiRoute
  '/compare/writesonic': typeof CompareWritesonicRoute
  '/compare/zillow': typeof CompareZillowRoute
  '/listing/$id': typeof ListingIdRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/canva': typeof CompareCanvaRoute
  '/compare/chatgpt': typeof CompareChatgptRoute
  '/compare/copyai': typeof CompareCopyaiRoute
  '/compare/curaytor': typeof CompareCuraytorRoute
  '/compare/dealmachine': typeof CompareDealmachineRoute
  '/compare/epique': typeof CompareEpiqueRoute
  '/compare/followupboss': typeof CompareFollowupbossRoute
  '/compare/grammarly': typeof CompareGrammarlyRoute
  '/compare/homebot': typeof CompareHomebotRoute
  '/compare/jasper': typeof CompareJasperRoute
  '/compare/kvcore': typeof CompareKvcoreRoute
  '/compare/listingai': typeof CompareListingaiRoute
  '/compare/listingrobot': typeof CompareListingrobotRoute
  '/compare/realtor': typeof CompareRealtorRoute
  '/compare/reimaginehome': typeof CompareReimaginehomeRoute
  '/compare/virtualstagingai': typeof CompareVirtualstagingaiRoute
  '/compare/writesonic': typeof CompareWritesonicRoute
  '/compare/zillow': typeof CompareZillowRoute
  '/listing/$id': typeof ListingIdRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/compare/canva'
    | '/compare/chatgpt'
    | '/compare/copyai'
    | '/compare/curaytor'
    | '/compare/dealmachine'
    | '/compare/epique'
    | '/compare/followupboss'
    | '/compare/grammarly'
    | '/compare/homebot'
    | '/compare/jasper'
    | '/compare/kvcore'
    | '/compare/listingai'
    | '/compare/listingrobot'
    | '/compare/realtor'
    | '/compare/reimaginehome'
    | '/compare/virtualstagingai'
    | '/compare/writesonic'
    | '/compare/zillow'
    | '/listing/$id'
    | '/blog/'
    | '/compare/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/compare/canva'
    | '/compare/chatgpt'
    | '/compare/copyai'
    | '/compare/curaytor'
    | '/compare/dealmachine'
    | '/compare/epique'
    | '/compare/followupboss'
    | '/compare/grammarly'
    | '/compare/homebot'
    | '/compare/jasper'
    | '/compare/kvcore'
    | '/compare/listingai'
    | '/compare/listingrobot'
    | '/compare/realtor'
    | '/compare/reimaginehome'
    | '/compare/virtualstagingai'
    | '/compare/writesonic'
    | '/compare/zillow'
    | '/listing/$id'
    | '/blog'
    | '/compare'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/compare/canva'
    | '/compare/chatgpt'
    | '/compare/copyai'
    | '/compare/curaytor'
    | '/compare/dealmachine'
    | '/compare/epique'
    | '/compare/followupboss'
    | '/compare/grammarly'
    | '/compare/homebot'
    | '/compare/jasper'
    | '/compare/kvcore'
    | '/compare/listingai'
    | '/compare/listingrobot'
    | '/compare/realtor'
    | '/compare/reimaginehome'
    | '/compare/virtualstagingai'
    | '/compare/writesonic'
    | '/compare/zillow'
    | '/listing/$id'
    | '/blog/'
    | '/compare/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareCanvaRoute: typeof CompareCanvaRoute
  CompareChatgptRoute: typeof CompareChatgptRoute
  CompareCopyaiRoute: typeof CompareCopyaiRoute
  CompareCuraytorRoute: typeof CompareCuraytorRoute
  CompareDealmachineRoute: typeof CompareDealmachineRoute
  CompareEpiqueRoute: typeof CompareEpiqueRoute
  CompareFollowupbossRoute: typeof CompareFollowupbossRoute
  CompareGrammarlyRoute: typeof CompareGrammarlyRoute
  CompareHomebotRoute: typeof CompareHomebotRoute
  CompareJasperRoute: typeof CompareJasperRoute
  CompareKvcoreRoute: typeof CompareKvcoreRoute
  CompareListingaiRoute: typeof CompareListingaiRoute
  CompareListingrobotRoute: typeof CompareListingrobotRoute
  CompareRealtorRoute: typeof CompareRealtorRoute
  CompareReimaginehomeRoute: typeof CompareReimaginehomeRoute
  CompareVirtualstagingaiRoute: typeof CompareVirtualstagingaiRoute
  CompareWritesonicRoute: typeof CompareWritesonicRoute
  CompareZillowRoute: typeof CompareZillowRoute
  ListingIdRoute: typeof ListingIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/zillow': {
      id: '/compare/zillow'
      path: '/compare/zillow'
      fullPath: '/compare/zillow'
      preLoaderRoute: typeof CompareZillowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/writesonic': {
      id: '/compare/writesonic'
      path: '/compare/writesonic'
      fullPath: '/compare/writesonic'
      preLoaderRoute: typeof CompareWritesonicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/virtualstagingai': {
      id: '/compare/virtualstagingai'
      path: '/compare/virtualstagingai'
      fullPath: '/compare/virtualstagingai'
      preLoaderRoute: typeof CompareVirtualstagingaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/reimaginehome': {
      id: '/compare/reimaginehome'
      path: '/compare/reimaginehome'
      fullPath: '/compare/reimaginehome'
      preLoaderRoute: typeof CompareReimaginehomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/realtor': {
      id: '/compare/realtor'
      path: '/compare/realtor'
      fullPath: '/compare/realtor'
      preLoaderRoute: typeof CompareRealtorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/listingrobot': {
      id: '/compare/listingrobot'
      path: '/compare/listingrobot'
      fullPath: '/compare/listingrobot'
      preLoaderRoute: typeof CompareListingrobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/listingai': {
      id: '/compare/listingai'
      path: '/compare/listingai'
      fullPath: '/compare/listingai'
      preLoaderRoute: typeof CompareListingaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/kvcore': {
      id: '/compare/kvcore'
      path: '/compare/kvcore'
      fullPath: '/compare/kvcore'
      preLoaderRoute: typeof CompareKvcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/jasper': {
      id: '/compare/jasper'
      path: '/compare/jasper'
      fullPath: '/compare/jasper'
      preLoaderRoute: typeof CompareJasperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/homebot': {
      id: '/compare/homebot'
      path: '/compare/homebot'
      fullPath: '/compare/homebot'
      preLoaderRoute: typeof CompareHomebotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/grammarly': {
      id: '/compare/grammarly'
      path: '/compare/grammarly'
      fullPath: '/compare/grammarly'
      preLoaderRoute: typeof CompareGrammarlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/followupboss': {
      id: '/compare/followupboss'
      path: '/compare/followupboss'
      fullPath: '/compare/followupboss'
      preLoaderRoute: typeof CompareFollowupbossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/epique': {
      id: '/compare/epique'
      path: '/compare/epique'
      fullPath: '/compare/epique'
      preLoaderRoute: typeof CompareEpiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/dealmachine': {
      id: '/compare/dealmachine'
      path: '/compare/dealmachine'
      fullPath: '/compare/dealmachine'
      preLoaderRoute: typeof CompareDealmachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/curaytor': {
      id: '/compare/curaytor'
      path: '/compare/curaytor'
      fullPath: '/compare/curaytor'
      preLoaderRoute: typeof CompareCuraytorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/copyai': {
      id: '/compare/copyai'
      path: '/compare/copyai'
      fullPath: '/compare/copyai'
      preLoaderRoute: typeof CompareCopyaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/chatgpt': {
      id: '/compare/chatgpt'
      path: '/compare/chatgpt'
      fullPath: '/compare/chatgpt'
      preLoaderRoute: typeof CompareChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/canva': {
      id: '/compare/canva'
      path: '/compare/canva'
      fullPath: '/compare/canva'
      preLoaderRoute: typeof CompareCanvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareCanvaRoute: CompareCanvaRoute,
  CompareChatgptRoute: CompareChatgptRoute,
  CompareCopyaiRoute: CompareCopyaiRoute,
  CompareCuraytorRoute: CompareCuraytorRoute,
  CompareDealmachineRoute: CompareDealmachineRoute,
  CompareEpiqueRoute: CompareEpiqueRoute,
  CompareFollowupbossRoute: CompareFollowupbossRoute,
  CompareGrammarlyRoute: CompareGrammarlyRoute,
  CompareHomebotRoute: CompareHomebotRoute,
  CompareJasperRoute: CompareJasperRoute,
  CompareKvcoreRoute: CompareKvcoreRoute,
  CompareListingaiRoute: CompareListingaiRoute,
  CompareListingrobotRoute: CompareListingrobotRoute,
  CompareRealtorRoute: CompareRealtorRoute,
  CompareReimaginehomeRoute: CompareReimaginehomeRoute,
  CompareVirtualstagingaiRoute: CompareVirtualstagingaiRoute,
  CompareWritesonicRoute: CompareWritesonicRoute,
  CompareZillowRoute: CompareZillowRoute,
  ListingIdRoute: ListingIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
