/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareListingaiRouteImport } from './routes/compare/listingai'
import { Route as CompareDealmachineRouteImport } from './routes/compare/dealmachine'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)

const CompareListingaiRoute = CompareListingaiRouteImport.update({
  id: '/compare/listingai',
  path: '/compare/listingai',
  getParentRoute: () => rootRouteImport,
} as any)

const CompareDealmachineRoute = CompareDealmachineRouteImport.update({
  id: '/compare/dealmachine',
  path: '/compare/dealmachine',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/explore': typeof ExploreRoute
  '/compare/': typeof CompareIndexRoute
  '/compare/dealmachine': typeof CompareDealmachineRoute
  '/compare/listingai': typeof CompareListingaiRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/explore': typeof ExploreRoute
  '/compare': typeof CompareIndexRoute
  '/compare/dealmachine': typeof CompareDealmachineRoute
  '/compare/listingai': typeof CompareListingaiRoute
  '/blog': typeof BlogIndexRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/explore': typeof ExploreRoute
  '/compare/': typeof CompareIndexRoute
  '/compare/dealmachine': typeof CompareDealmachineRoute
  '/compare/listingai': typeof CompareListingaiRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pricing' | '/privacy' | '/terms' | '/explore' | '/compare/' | '/compare/dealmachine' | '/compare/listingai' | '/blog/' | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pricing' | '/privacy' | '/terms' | '/explore' | '/compare' | '/compare/dealmachine' | '/compare/listingai' | '/blog' | '/blog/$slug'
  id: '__root__' | '/' | '/pricing' | '/privacy' | '/terms' | '/explore' | '/compare/' | '/compare/dealmachine' | '/compare/listingai' | '/blog/' | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ExploreRoute: typeof ExploreRoute
  CompareIndexRoute: typeof CompareIndexRoute
  CompareDealmachineRoute: typeof CompareDealmachineRoute
  CompareListingaiRoute: typeof CompareListingaiRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/dealmachine': {
      id: '/compare/dealmachine'
      path: '/compare/dealmachine'
      fullPath: '/compare/dealmachine'
      preLoaderRoute: typeof CompareDealmachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/listingai': {
      id: '/compare/listingai'
      path: '/compare/listingai'
      fullPath: '/compare/listingai'
      preLoaderRoute: typeof CompareListingaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ExploreRoute: ExploreRoute,
  CompareIndexRoute: CompareIndexRoute,
  CompareDealmachineRoute: CompareDealmachineRoute,
  CompareListingaiRoute: CompareListingaiRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
